### ISSUE TITLE
Filtering strategy (instead of iterating ray samples) for traverse_grids?

### ISSUE THREAD

**Issue by Yosshi999** [nerfstudio-project/nerfacc#269]
Currently `traverse_grids` samples points by proceeding the ray little by little, but in this strategy the sampled points are sometimes located at a vacuum voxel (I mean the voxel where `binaries[voxel_id]` is False) because of float errors. I think you are aware of this according to the comment [here](https://github.com/nerfstudio-project/nerfacc/blob/master/nerfacc/cuda/csrc/include/utils_grid.cuh#L71).

In contrast to this, we can avoid the error when we sample all points on a ray and then filter points where `binaries[voxel_id]` is False or outside of the aabb.
Do you think this will cause a performance drop or other problems?  I'm interested in implementing this strategy if it is reasonable.

**Comment by liruilong940607** [comment]
This is likely to bring a bit performance drop but more important would lead to more memory usage because you would need to allocate memory for all samples -- and this can be pretty wasteful of memory usage if the space is sparse enough.

In practice, however, network would be the bottleneck for both speed and memory allocation so I would expect not too much of difference between the two
